# Generated by Django 5.0.3 on 2024-03-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_remove_team_captain_name_team_captain_team_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countDown', models.DateField(null=True)),
                ('team1Wins', models.IntegerField(default=0)),
                ('team2Wins', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('i', 'inProgress'), ('s', 'scheduled'), ('v', 'void'), ('f', 'finished')], max_length=1, null=True)),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team1Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='team.team')),
                ('team2Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=128)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('matchDetail', models.CharField(blank=True, max_length=255)),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='court_schedules', to='match.matchtable')),
            ],
        ),
    ]
