# Generated by Django 5.0.3 on 2024-04-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_matchtable_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtschedule',
            name='endTime',
        ),
    ]
