# Generated by Django 5.0.3 on 2024-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_courtschedule_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='status',
            field=models.CharField(choices=[('s', 'scheduled'), ('i', 'inProgress'), ('r', 'reported'), ('f', 'finished'), ('v', 'void')], max_length=1, null=True),
        ),
    ]
