# Generated by Django 5.0.3 on 2024-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_remove_matchtable_team1wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtable',
            name='scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='matchtable',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
