# Generated by Django 5.0.3 on 2024-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_captain_name_team_captain_team_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
