# Generated by Django 5.0.3 on 2024-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0003_division_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamindivision',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
