# Generated by Django 5.0.3 on 2024-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0004_alter_teamindivision_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='status',
            field=models.CharField(choices=[('n', 'notStated'), ('i', 'inProgress'), ('f', 'finished'), ('v', 'void')], max_length=1, null=True),
        ),
    ]
