# Generated by Django 5.0.3 on 2024-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0005_division_description_alter_division_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
