# Generated by Django 5.0.3 on 2024-04-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0007_division_end_date_division_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='defaultLocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
