# Generated by Django 5.0.3 on 2024-04-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0009_division_group_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='challengeDistance',
            field=models.IntegerField(default=1),
        ),
    ]
